sudo: false
language: php
php:
- '7.0'
- '7.1'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: '7.1'
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: K55i9UC0GNsUEF+NkjtnwSSePzw4SgamskYoBhJ0hd5GQjDRFK3LwOEz3MxMgQFiTqtIqR9MRUKUOlSPUrtnkgae21SVjDOi/9IuQVP1+JrUjf17EhebK+pmpYpFo6K7JS7rdLf4PSnTzY1LOH/EFCyyTM9IExhyX25Z+LhopV8rjiPorNTYVWO32c4hZJA03JJIhXnAlqDL5hbOQhXq8oq5S4cvDaC4qZ/hATA+ZKJ10Gf0JEsCuEnHoAPjIB/Tpp6euNwO1C1uUH9yHYSXf0PTzyPuRJoViX9hmZErCoL3bCSJLqd9giWatOlsogMI1ahK3fLWzyM/oI8c4Cn14bIp8oImGEmzT4+CxtGbBtEysL9I8SBxnpK0N6OIwtIjsLf0lh+R6aMSXZCQgyX84OraTI+LitMD0zpUCyD0kMjuk8CHG9fTbYYNAtLOomTF1C6wt+7Infqf/hhOn1DhMEcYjurBffQBHDYqsN3jm0x74pyVc3963ax/6W+oKm/EgezCzGeNc1wG+xsAFgfqZ8GVIxe5+m27eVwBV//mpggza5Nh4LPMa9u9hJq+BeacyHaf2uTlmpaCIF5jWah03CgsuK+KVj5Fhb7pPW8B9TopYPjFAIvBuZSERGEiC+Ynv5xkHMFX33sKIUirOgom8f7XQzk2Meu7xHpfR2lehN4=
cache:
  directories:
  - $HOME/.composer
