sudo: false
language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: A908c0IJazGPYkSOn4x+F6OBx/g8yIqcq5/+2JngzKik41lqlIvopC8qMnVjRRhdWZSJEX/LW1vfScQIVkpqOdAauo6SUGVL83ZgmbI9tiVDOSoNURPi8H7U6KpOtsbTz7alxzNVmt6yx5/pJrSwHTkWYbZ7B1P+mBIkkI+JcX3mGb6IARhuMvGpnw6jvKSjWID0IaGuMZPXthDmy6aGvYZoJ3LjcO3zJi0/V++t2ohCQx6gzAZj6NkVZ1sXI5x0qz9OXJzekIO62RsDw7mP2vti1uqj8Vj1Q32EZ02ARIUwukHC8hG+hIiqv+lvQ6kXI1a8OeZ0WeCM8jlbYcPO9r4FvEWEILy/S5ok/38DR/vK1Lt9UW+791zv2+TkKpkpA3wbjrTc7thFrRho96AnoUP0HUQNi8F1jISUedCKZ3DPfj/Px3IYv20Br+IS40VizAtAupjewBsSBGPv1xOtfM4UhFMXqeOV+3Zcj1kXWtREb4+wQ13vgpX3VXZZlXykMu0Y9ZMBDwK2RRSdqBtDh+XGNBpefETN8Uy8mhXLnLkvqVKCKyttZe26usBFHc+x37UsSeUSwPGYChY2kZuKqtAobCIV17tLQroJWnc9vql54uGQO0/qJvg7L0QCKSLPF5valRlf939xcHwAE+DzlNEWP/ILLyNeHpCR3/3avDo=
cache:
  directories:
  - $HOME/.composer
