sudo: false
language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- "[[ $GITHUB_TOKEN ]] && composer config --global github-oauth.github.com $GITHUB_TOKEN"
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: Icjiel2wuv0grOKETxphS2dFymQkiQ58AnuRUgMHyCiJD+GHuC50opSdvT0qvEaToVsER7JdmyoFqambPPJI/kHlgp1a1AoKc2NMVQSPq9E4SWjCZlKW29mEpWrj/MJxlcEjK9y20UHMCBRjh19588LdQ1dD2vkIdFqaqmuY/k/lC7/3UUsyZxu4BCRBSkWTSYuGE0ql9pnyHSpYoApU/WvuONQPjCTGpC3EoGMaY1tXdw8osZrkSmR/AAWCSeL3PVD0Ezc1UaGbJ5MYhq+WqjGwE6YoFlZcLdD64YpKHjfVUzXg4vf5tMXFAXpBM/oa8HjSGGhc6/nQIiPipxLJnkxphLxmzMIO5OKRaV14O1Ek3YogA5BIAq8a0FwHAR4QrVoQHc5eeLXECXaCNr+uEGvCi7q27xFIW1gCB0Re24OewLTyw2r6RPq+mvw7nGcAq2imvSyTz3LaI+KJsJhSIGl1ghtW5iUhn2lyxOOmC95OFzzTuiuSlHqFaq5Ehim7Lu9hQJ7A20GFynHzQhTl31Vg9Me1qVXaeW6Zlzb/Yiz2uXig/Si1XMw8V22v77IagA29wV7HdU2lJ/ThfQOr48z96z3C48j/9Y8x252LH7o6jBVh0T/e4Yyv6W2aOMcTe2GXnRlluKIYoWl5PJvQXBX8ti8HyZVugaJgXsj7nOg=
cache:
  directories:
  - "$HOME/.composer/cache/files"
